<<<<<<< HEAD
# Generated by Django 5.0 on 2024-01-31 17:15
=======
# Generated by Django 5.0 on 2024-01-31 17:19
>>>>>>> 69ca8cc4a75cbc290432daa0d83198401e46c13d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
